;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-sub-or-superscript
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        coffee-dedent-line-backspace
        forward-sexp
        haskell-indentation-delete-backward-char
        haskell-indentation-delete-char
        indent-for-tab-command
        js2r-extract-var
        kill-region
        org-self-insert-command
        paredit-forward-delete
        prelude-move-beginning-of-line
        prelude-smart-open-line
        scroll-down-line
        sgml-slash
        smex
        sp--self-insert-command
        tern-ac-dot-complete
        ))

(setq mc/cmds-to-run-once
      '(
        scroll-up-line
        ))
